const ALLOWED_VIDEO_MIME_TYPES = ['video/mp4', 'video/quicktime', 'video/webm'];
const MAX_UPLOAD_SIZE_BYTES = 1073741824; // 1GB
const MIN_WATCH_SECONDS = 5;
const MAX_VIEWS_PER_IP_PER_HOUR = 10;
const MIN_WITHDRAWAL_AMOUNT = 100;
const DEFAULT_EARNINGS_PER_VIEW = 0.13;
const CURRENCY = 'USD';
const SHORT_CODE_LENGTH = 8;
const UPLOAD_INTENT_EXPIRY_MINUTES = 30;
const SIGNED_URL_EXPIRY_SECONDS = 3600;

module.exports = {
  ALLOWED_VIDEO_MIME_TYPES,
  MAX_UPLOAD_SIZE_BYTES,
  MIN_WATCH_SECONDS,
  MAX_VIEWS_PER_IP_PER_HOUR,
  MIN_WITHDRAWAL_AMOUNT,
  DEFAULT_EARNINGS_PER_VIEW,
  CURRENCY,
  SHORT_CODE_LENGTH,
  UPLOAD_INTENT_EXPIRY_MINUTES,
  SIGNED_URL_EXPIRY_SECONDS
};
