const USER_ROLES = {
  CREATOR_ADMIN: 'CREATOR_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN'
};

const USER_STATUS = {
  ACTIVE: 'ACTIVE',
  BLOCKED: 'BLOCKED'
};

const VIDEO_TYPE = {
  DIRECT_UPLOAD: 'DIRECT_UPLOAD',
  EXTERNAL_REF: 'EXTERNAL_REF'
};

const VIDEO_STATUS = {
  UPLOADING: 'UPLOADING',
  READY: 'READY',
  FAILED: 'FAILED',
  DELETED: 'DELETED'
};

const UPLOAD_STATUS = {
  INITIATED: 'INITIATED',
  UPLOADED: 'UPLOADED',
  VERIFIED: 'VERIFIED',
  EXPIRED: 'EXPIRED',
  FAILED: 'FAILED'
};

const PLAYBACK_SESSION_STATUS = {
  STARTED: 'STARTED',
  ACTIVE: 'ACTIVE',
  QUALIFIED: 'QUALIFIED',
  REJECTED: 'REJECTED',
  CLOSED: 'CLOSED'
};

const PLAYBACK_EVENT_TYPE = {
  PAGE_OPEN: 'PAGE_OPEN',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  PROGRESS: 'PROGRESS',
  SEEK: 'SEEK',
  END: 'END',
  HEARTBEAT: 'HEARTBEAT',
  COMPLETE: 'COMPLETE'
};

const VIEW_TYPE = {
  VALID: 'VALID',
  REJECTED: 'REJECTED'
};

const WALLET_TRANSACTION_TYPE = {
  VIEW_EARNING: 'VIEW_EARNING',
  WITHDRAWAL_REQUEST: 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_PAID: 'WITHDRAWAL_PAID',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  ADJUSTMENT: 'ADJUSTMENT'
};

const WITHDRAWAL_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};

/** Stored on withdrawal requests after validation (normalized to uppercase). */
const PAYMENT_METHOD_TYPE = {
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER',
  PAYPAL: 'PAYPAL'
};

const AUDIT_ENTITY_TYPE = {
  USER: 'USER',
  VIDEO: 'VIDEO',
  WITHDRAWAL: 'WITHDRAWAL',
  LINK: 'LINK',
  SYSTEM: 'SYSTEM'
};

const AUDIT_ACTION = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ALL: 'USER_LOGOUT_ALL',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  VIDEO_CREATED: 'VIDEO_CREATED',
  VIDEO_UPDATED: 'VIDEO_UPDATED',
  VIDEO_DELETED: 'VIDEO_DELETED',
  LINK_CREATED: 'LINK_CREATED',
  LINK_TOGGLED: 'LINK_TOGGLED',
  WITHDRAWAL_REQUESTED: 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED: 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED: 'WITHDRAWAL_REJECTED',
  WITHDRAWAL_PAID: 'WITHDRAWAL_PAID',
  ADMIN_BLOCK_USER: 'ADMIN_BLOCK_USER',
  ADMIN_UNBLOCK_USER: 'ADMIN_UNBLOCK_USER',
  ADMIN_VIDEO_DELETED: 'ADMIN_VIDEO_DELETED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED'
};

module.exports = {
  USER_ROLES,
  USER_STATUS,
  VIDEO_TYPE,
  VIDEO_STATUS,
  UPLOAD_STATUS,
  PLAYBACK_SESSION_STATUS,
  PLAYBACK_EVENT_TYPE,
  VIEW_TYPE,
  WALLET_TRANSACTION_TYPE,
  WITHDRAWAL_STATUS,
  PAYMENT_METHOD_TYPE,
  AUDIT_ENTITY_TYPE,
  AUDIT_ACTION
};
